stages:
- test

build-fedora:
  image: fedora:latest
  stage: test
  before_script:
    - dnf install -y gcc redhat-rpm-config which make automake autoconf libarchive-devel libxml2-devel gdk-pixbuf2-devel glib2-devel
  script:
    - ./autogen.sh --disable-dependency-tracking
    - make
    - make install

